repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
        args:
            - --in-place
            - --remove-duplicate-keys
            - --remove-unused-variables
            - --ignore-init-module-imports
            - --remove-all-unused-imports
            - --expand-star-imports
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.7
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
    -   id: ruff-format
